sudo: required
dist: trusty
language: python
python:
    - "3.4"
env:
    - RASPBIAN_VERSION="2017-07-05-17:42"
before_install:
    - sudo apt-get update
    - sudo apt-get install qemu-user-static xz-utils binfmt_support
script:
    - sh install-dependencies.sh
